### ISSUE TITLE
bug in `.save_parquet` in `append` mode

### ISSUE THREAD

**Issue by kellyjoy15** [Bears-R-Us/arkouda#1304] opened 2022-04-19 18:32 UTC
Documentation is [here](https://bears-r-us.github.io/arkouda/autoapi/arkouda/pdarrayclass/index.html?highlight=parquet#arkouda.pdarrayclass.pdarray.save)
When using file_format='Parquet', I got the following error:
"TypeError: got an unexpected keyword argument 'file_format'"

**Comment by bmcdonald3** [comment] 2022-04-19 19:04
Thank you for reporting this, are you seeing this when attempting to save a strings array? It seems that the code for the string pdarrays does not yet have the `file_format` keyword, so you still need to use `save_parquet()` on string arrays unfortunately. 

I am working on a fix for this now and will have the `file_format` keyword working on strings shortly. Sorry about that!

**Comment by kellyjoy15** [comment] 2022-04-19 19:20
The arkouda version is v2022.04.15

It's not a string array, just int64.
Here is a reproducer. Please forgive any typos. I am typing this in manually.

data = ak.array(list(range(0,2000))
data.save(prefix_path=file_prefix, dataset='foo', mode='append', file_format='Parquet')

**Comment by bmcdonald3** [comment] 2022-04-19 19:27
The `file_format` keyword change was actually just merged today, so I think you will just need to use `save_parquet` instead for the time being. So it would instead be:

```
data = ak.array(list(range(0,2000))
data.save_parquet(prefix_path=file_prefix, dataset='foo', mode='append')
```
And that should work for you.

Does the branch that you are running on have the latest changes? (i.e., changes from the last few hours)

I think the documentation is just one step ahead here, but I believe the `save_parquet` function should fix your problem.

**Comment by pierce314159** [comment] 2022-04-19 19:33
Awesome! Yeah @kellyjoy15 based on the version number, these changes won't reach you until the next release. Hopefully in the meantime, the workaround @bmcdonald3 suggested will do

**Comment by kellyjoy15** [comment] 2022-04-19 19:35
Thanks. Unfortunately, I only tried plain "save" because save_parquet doesn't seem to work with mode='append'.

**Comment by pierce314159** [comment] 2022-04-19 19:48
It seems like the `save_parquet` in `append` mode bug is overlapping with #1303. I think we should track that here

@kellyjoy15, does
```python
data = ak.array(list(range(0,2000))
data.save_parquet(prefix_path=file_prefix, dataset='foo', mode='append')
```
work as a reproducer for the bug or can you provide one?

**Comment by kellyjoy15** [comment] 2022-04-19 19:57
yes, the above works as a reproducer. Sorry for my confused issue creation. What I really want is 1303, and I found bugs while trying to make a workaround.

**Comment by kellyjoy15** [comment] 2022-04-19 20:00
I believe the issue is with "append" when the file doesn't already exist.

**Comment by pierce314159** [comment] 2022-04-19 20:00
No problem! We appreciate you letting us know about the bug and the enhancement :)

**Comment by pierce314159** [comment] 2022-04-19 20:02
> I believe the issue is with "append" when the file doesn't already exist.

Ah, I think there's a good chance that this might be solved by PR #1296, if so this will be in the next release.

**Comment by bmcdonald3** [comment] 2022-04-19 20:22
Hi @kellyjoy15, sorry about the confusion here, the Parquet work is very new, so I think we all get a little excited seeing that it was seeing some use!

I believe that I am now understanding the problem and have typed up a short sample program that shows the intended usage of writing/reading Parquet files and using the `append` mode:

```python3
a = ak.array([1, 2, 3, 4, 5])
b = ak.array([1.1, 2.2, 3.3, 4.4, 5.5])
c = ak.array(['str1', 'str2', 'str3', 'str4', 'str5'])

# The first created file must be created with `mode='truncate'` (which is the default)
a.save_parquet(prefix_path="test-file", dataset='col1', mode='truncate')

# Subsequent arrays to be appended must be written with `mode='append'` 
# and have the same number of elements as the first array
b.save_parquet(prefix_path="test-file", dataset='col2', mode='append')
c.save_parquet(prefix_path="test-file", dataset='col3', mode='append')

ak.read_parquet('test-file*')
# The result of this call:
# {'col3': array(['str1', 'str2', 'str3', 'str4', 'str5']), 'col2': array([1.1000000000000001 2.2000000000000002 3.2999999999999998 4.4000000000000004 5.5]), 'col1': array([1 2 3 4 5])}
```

If you had a collection of pdarrays you wanted to write all to a table, you had the right idea of just using a `for` loop with `mode='append'`, but the first file still needs to be created with `mode='truncate'`, so you would need to either create that in advance or have a check in the loop to see if it is the first iteration and determine the mode like that.

If this does not help with your problem, please let me know and I will try to work out the issue that you are seeing. If you were expecting different behavior, I would appreciate some feedback on the API either in this thread or in the form of a new issue. Hope this helps!

**Comment by kellyjoy15** [comment] 2022-04-19 21:06
I was able to make it work using truncate for the first column. I would have expected 'append' to work like writing to a file in append mode. That is, it creates a file if none exists and appends to the file if it does exist. Maybe do a quick poll or something to see if I am in the minority? Either way, I got it to work.

**Comment by bmcdonald3** [comment] 2022-04-19 21:15
Glad to hear you got it to work.

I think you make a good point about writing with `append` to a non-existent file should create it, I am not sure why it has the behavior that it does today and I'll be sure to bring that up with some of the other Arkouda developers. Thanks.

**Comment by pierce314159** [comment] 2022-04-19 21:24
Closing this issue since we got this working and have an issue tracking `mode='append'`s behavior with non-existent files

**Closed by pierce314159** 2022-04-19 21:24 UTC
Labels: bug, important
