### ISSUE TITLE
Nested parquet fields causing server crash

### ISSUE THREAD

**Issue by 21771** [Bears-R-Us/arkouda#2396] opened 2023-04-25 19:57 UTC
**Describe the bug**
Reading parquet files containing fields with nested data causes server to crash. These fields were just ignored in previous versions.

**Comment by Ethan-DeBandi99** [comment] 2023-04-25 20:01
@21771 - when you say nested data are you referring to things like SegArray?

**Comment by 21771** [comment] 2023-04-25 20:10
These are files created by other programs that columns with nested fields. Arkouda has read these files in the past without problems. To read the same files we read before, with v2023.04.07 we need to explicitly list all of the columns except the ones containing nested fields.

**Comment by 21771** [comment] 2023-04-25 20:14
Note: this is a great segue for requesting from_pandas() with simple (numeric) list and addition of some type of string representation in segarrays. I'll submit separate feature requests for those.

**Comment by 21771** [comment] 2023-04-25 20:18
Not related ... but thanks for the string to int functionality. Not sure how long it's been there, but that was a nice discovery. Using splits and segarrays it's provided a great way to do IP string to numeric conversions for IPv4 and IPv6.

**Comment by Ethan-DeBandi99** [comment] 2023-04-26 11:15
@21771 - I think I know what is happening here. The request for SegArray support in Parquet requires the reading writing of nested data because SegArray is actually stored as its segments to conform to Parquet standards. If I alter this code to ensure that the files load without explicitly loading the columns you want, the ability to read/write SegArray will be lost. 

Maybe there is something specific about the fields causing the issue that can be used to identify them.

**Comment by Ethan-DeBandi99** [comment] 2023-04-26 14:45
@21771 - might need a bit more info here. Do you know how many levels nested the data is? If it is more than 1, I am able to generate an error, but not able to reproduce the server crashing.

**Comment by Ethan-DeBandi99** [comment] 2023-04-26 15:33
Ok I think I have an idea for an adjustment to the API to make this work in both cases. For `read_parquet` I would like to add a `read_segarray` flag that defaults to true so that SegArrays from Arkouda remain functional. When the Flag is set to `False`, any nested columns will be skipped. This should allow you to read in the files in question exactly as you did before without needing to explicitly list the columns to read from the file.

I am going to go ahead and put this implementation together. If you have any concerns with this implementation, please let me know and I can go back to the drawing board on it.

**Comment by 21771** [comment] 2023-04-26 18:05
That sounds like a good plan. Thank you.

**Comment by Ethan-DeBandi99** [comment] 2023-04-26 18:06
@21771 - Great! No problem. The PR is up and it will be included in the next release.

**Closed** 2023-04-27 17:12 UTC
Labels: bug, In Progress, User Reported, File IO
