### ISSUE TITLE
`Datetime.floor` not handling `NaT` values properly

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#2634] opened 2023-08-03 11:59 UTC
`Datetime.floor` is not treating `NaT` values properly and is returning bogus dates from the year 1677. 

**Reproducer**
```python
a = ak.Datetime(ak.ones(10, dtype=ak.int64)*-9223372036854775808) #that's approximately the NaT value 
a.floor("day")
```

**Comment by stress-tess** [comment] 2024-10-25 21:26
duplicate of #2753

**Closed by stress-tess** 2024-10-25 21:26 UTC
Labels: bug, User Reported
