### ISSUE TITLE
src file location for #1799

### ISSUE THREAD

**Issue by 21771** [Bears-R-Us/arkouda#1875] opened 2022-11-01 20:48 UTC
When attempting to use idna_encode() and idna_decode() recieve runtime error looking for file <user_dir>/src/exec/0_tmp.txt and <user_dir>/src/exec/2_tmp.txt. 

No "src/exec" directory exists under the user directory. Is there a variable we need to set to point to the correct location to enable this to work?

Thanks for implementing this!

**Comment by Ethan-DeBandi99** [comment] 2022-11-02 11:51
@21771 - I will be looking into this today. I have a fairly good idea of what is happening. I know there were a few things I had to work around initially with the file write. I know the intended workflow was for it to save files in `/<path_to_arkouda>/arkouda/src/exec/tmp.txt`. However, from your description above it seems that it is looking at your user directory. I need to dig into why that is happening.

For awareness, we also have a more permanent solution in the pipeline coming soon. Either way, we will get a solution to you as soon as possible.

**Comment by Ethan-DeBandi99** [comment] 2022-11-02 12:02
@21771 - I do have a few clarifying questions as my initial thought was not the cause.

- Are you running Arkouda locally or connecting to a remote server? I am worried that if you are calling to a remote server somehow the python that should be running on the server may be trying to run on your machine.
- Is there any way you can get me the exact line number? I am curious if this is occurring during the file write or reading back out.

Sorry if I am getting to into the weeds here, I just want to make sure I am recording what I am thinking for future reference.

**Comment by Ethan-DeBandi99** [comment] 2022-11-02 14:01
@21771 - I was able to reproduce this on my machine. Looking into solutions for you now.

**Comment by 21771** [comment] 2022-11-02 14:29
Thanks! If the questions is still relevant, I am running on a remote server.

**Comment by 21771** [comment] 2022-11-02 14:35
RuntimeErrors on lines 361 & 365

**Comment by Ethan-DeBandi99** [comment] 2022-11-02 14:37
> RuntimeErrors on lines 361 & 365

Thanks!

**Comment by Ethan-DeBandi99** [comment] 2022-11-08 16:41
@21771 - I just confirmed, you will need to copy `/src/exec` into your user directory from the Arkouda install location. Once you do this, you will have `/user_dir/src/exec/`. Make sure to copy the contents as well because there are python scripts in the `exec` folder that you will need.

I apologize, this is a temporary work around until codecs are supported in Chapel.

**Comment by 21771** [comment] 2022-11-08 19:54
Thanks! Really appreciate the work on this!
That workaround gets around this the src file location issue.

However, two new bugs for actual operation:
1) Empty strings cause SIGTERM(15) for idna_encode() or idna_decode(). Should return empty strings since we can't control whether they exist or not.
2) decode of ascii strings returns empty string instead of self. example ak.array(['example.com']).idna_decode() should return original array.

Again, thanks for providing this capability.

**Comment by Ethan-DeBandi99** [comment] 2022-11-09 15:51
@21771 - Glad that solved it. I am going to close this issue and open a new one to address the other bugs you noted. I will tag you in those issues for your awareness.

**Closed** 2022-11-09 15:57 UTC
Labels: bug, In Progress
