### ISSUE TITLE
_get_head_tail_server in DataFrame dropping types when DataFrame exceeds pandas max_rows 

### ISSUE THREAD

**Issue by brentcastle** [Bears-R-Us/arkouda#1831] opened 2022-10-11 22:15 UTC
Categorical, SegArray, and Strings are preserved, but at a minimum Fields, IPv4, and Datetime were not preserved. This happened when an arkouda DataFrame had those types, exceeded pandas max_rows, and then the corresponding arrays in the DataFrame would be either uint64 or int64 (I don't recall which) when displayed in a notebook. Incidentally, it also seems like there is an issue with Strings or perhaps only when there are multiple Strings arrays where the offsets are potentially incorrect. This causes an element in a Strings array to only display part of the string and/or the string from an incorrect row. I can try to generate a simpler exemplar if needed, but this occurred in a relatively small arkouda DataFrame with multiple Strings arrays.

**Comment by Ethan-DeBandi99** [comment] 2022-10-12 14:59
@brentcastle - I have Fields, IPv4, and Datetime working properly now. I also took care of BitVector. I am not able to reproduce the issue you were seeing with Strings. Can you please provide a reproducer for the String offset issue you are seeing? Thanks!

**Comment by pierce314159** [comment] 2022-10-12 21:03
Hi @brentcastle! Thanks so much for pointing this out! This will be fixed by PR #1833

**Closed** 2022-10-13 16:38 UTC
Labels: bug, In Progress
